### PR TITLE
Sort app list alphabetically in asc or desc order

### PR DESCRIPTION
**Pull request by nitishSr**

### CODE REVIEW

**Comment by nitishSr** [comment]
@sshveta , @ganeshhubale please review this PR

**Comment by nitishSr** [comment]
> @sshveta , @ganeshhubale please review this PR

**Comment by ganeshhubale** [comment]
@nitishSr 
- I can see that you first click on dropdown button and then select 'Name' or 'Story'.
- You already have dropdown widget defined - https://github.com/windup/windup_integration_test/pull/72/files#diff-36bc2dbdeb3131e7bb627b8d983a8bfe5e3e6ae7fd591d3204cb07a52aca8382R25
- So IMO, please try other dropdown widgets and make sure that, this widget only clicks on the buttons and select values.
- So that, we will not need new button defined for just clicking/opening the dropdown.

**Comment by nitishSr** [comment]
> @nitishSr
> 
> * I can see that you first click on dropdown button and then select 'Name' or 'Story'.
> * You already have dropdown widget defined - https://github.com/windup/windup_integration_test/pull/72/files#diff-36bc2dbdeb3131e7bb627b8d983a8bfe5e3e6ae7fd591d3204cb07a52aca8382R25
> * So IMO, please try other dropdown widgets and make sure that, this widget only clicks on the buttons and select values.
> * So that, we will not need new button defined for just clicking/opening the dropdown.

@ganeshhubale, changes done.

**Comment by ganeshhubale** [comment]
LGTM :)

**Pull request merged**
