### PR TITLE
Added test case to automate application list sorting

### PR DESCRIPTION
**Pull request by nitishSr**
Test case for sorting applications list by name and story points. 

1. Create project with app list - [
            "acmeair-webapp-1.0-SNAPSHOT.war",
            "cadmium-war-0.1.0.war",
            "bw-note-ear-4.0.0.ear",
        ]
2. Run analysis
3. Open applications list page
4. Sort by name (arranges apps alphabetically)
5. Sort by story points (arranges in increasing order of story points)
6. Modified DropdownMenu Widget for selecting sort dropdown
7. Added new method to sort based on sort criteria

### CODE REVIEW

**Review by sshveta — CHANGES_REQUESTED** [review]
Looks good Nitish , please run pre commit checks and also paste result of your test run for this test .

**Comment by nitishSr** [comment]
@sshveta, pre-commit check passed and uploaded test case pass result.
test_result

**Comment by ganeshhubale** [comment]
@nitishSr 
we have two test cases with same same
```
mta/tests/test_applications.py::test_sort_applications ERROR
mta/tests/test_report.py::test_sort_applications
```
Can you please update your test case name!

**Comment by nitishSr** [comment]
> @nitishSr
> we have two test cases with same same
> 
> ```
> mta/tests/test_applications.py::test_sort_applications ERROR
> mta/tests/test_report.py::test_sort_applications
> ```
> 
> Can you please update your test case name!

Done @ganeshhubale

**Review by ganeshhubale — APPROVED** [review]
Thanks for PR @nitishSr 
Looks good to me :)

**Pull request merged**
